### ISSUE TITLE
misleading error msg

### ISSUE THREAD

**Issue by hugobowne** [datacamp/projects-discovery-of-handwashing-python#16]
@rasmusab i've completed the handwashing project and loved it. i have more feedback coming but, before i forget, in task 8 it threw this error:

<img width="1183" alt="screenshot 2017-12-04 14 11 02" src="https://user-images.githubusercontent.com/4182382/33571490-1de968ac-d8fe-11e7-8cf9-e7a1d5b8eda6.png">

however, my confidence interval call was fine. it was the argument to `.append()` that wasn't quite correct. it took me a while to realise what was going on. I would have reported this in the project but a screenshot is worth 100 lines of code

**Comment by rasmusab** [comment]
It's difficult to write tests! :) Good suggestion. I've change it now so that which way you subtract stuff in the append statement is fine.

**Comment by vshiv667** [comment]
@rasmusab I just kicked off my R learning's on this project. Getting an error for Q6.

# From this date handwashing was made mandatory
handwashing_start = as.Date('1847-06-01')

# Add a TRUE/FALSE column to monthly called handwashing_started
monthly<-monthly%>%mutate(handwashing_started = date >= handwashing_start)

# Plot monthly proportion of deaths before and after handwashing
monthly<-ggplot(monthly, aes (x=proportion_deaths, y=date, color=handwashing_started)) + geom_line()
monthly + labs(x='Proportion of Deaths', y='Date')

**Comment by davidventuri** [comment]
cc: @erinann

**Comment by rasmusab** [comment]
Hi @vshiv667 ,

It seems you are doing the R-version of the project, but this repo is for the python version. Also, it seems you've missed pasting in the actual error message. :)

All best,
Rasmus

**Comment by vshiv667** [comment]
Hi Rasmus

Yikes !
This is the error and I am doing the R-version of the project on Data Camp.

[cid:8a837666-dd2d-4e37-8293-1775bd87720e]
________________________________

**Comment by erinann** [comment]
Hello @vshiv667 ,

If you find an error in the project, please give feedback by clicking on the "Report an Issue" option in the top right of the project and providing the appropriate information. 

![image](https://user-images.githubusercontent.com/35779957/68634232-c300d680-04c2-11ea-96d1-cfc6766cb12e.png)
